// ============================================================
// Demo Mode Data - realistic mock data for the hackathon demo
// ============================================================

import {
  User,
  Account,
  Transaction,
  PaymentLink,
  Recipient,
  Settlement,
  DashboardStats,
  ChartDataPoint,
} from "@/types";

export const DEMO_USER: User = {
  id: "demo-user-001",
  email: "ade@adebayodesigns.com",
  full_name: "Adebayo Okonkwo",
  business_name: "Adebayo Designs",
  avatar_url: undefined,
  country: "NG",
  created_at: "2024-01-15T10:00:00Z",
  kyc_status: "verified",
};

export const DEMO_ACCOUNT: Account = {
  id: "demo-acct-001",
  user_id: "demo-user-001",
  balance_usd: 12_847.5,
  balance_local: 19_884_225,
  local_currency: "NGN",
  is_demo: true,
};

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: "txn-001",
    account_id: "demo-acct-001",
    type: "incoming",
    amount: 1500,
    currency: "USD",
    status: "completed",
    description: "Brand identity project payment",
    reference: "BP-2024-0892",
    sender_name: "Marcus Webb",
    sender_email: "marcus@techflow.io",
    payment_link_id: "pl-001",
    created_at: "2024-07-18T14:23:00Z",
  },
  {
    id: "txn-002",
    account_id: "demo-acct-001",
    type: "incoming",
    amount: 750,
    currency: "USD",
    status: "completed",
    description: "Website redesign - 50% deposit",
    reference: "BP-2024-0891",
    sender_name: "Priya Sharma",
    sender_email: "priya@fintechco.com",
    created_at: "2024-07-17T09:11:00Z",
  },
  {
    id: "txn-003",
    account_id: "demo-acct-001",
    type: "incoming",
    amount: 2800,
    currency: "USD",
    status: "completed",
    description: "Annual subscription design system",
    reference: "BP-2024-0885",
    sender_name: "Cloudnine SaaS",
    sender_email: "accounts@cloudnine.com",
    created_at: "2024-07-15T16:45:00Z",
  },
  {
    id: "txn-004",
    account_id: "demo-acct-001",
    type: "settlement",
    amount: 3200,
    currency: "USD",
    status: "completed",
    description: "Settlement to GTBank ****1234",
    reference: "SET-2024-0045",
    created_at: "2024-07-14T08:00:00Z",
    settled_at: "2024-07-14T10:32:00Z",
  },
  {
    id: "txn-005",
    account_id: "demo-acct-001",
    type: "incoming",
    amount: 320,
    currency: "USD",
    status: "pending",
    description: "Logo refresh package",
    reference: "BP-2024-0899",
    sender_name: "Kofi Mensah",
    sender_email: "kofi@ghanafintech.co",
    created_at: "2024-07-19T11:05:00Z",
  },
  {
    id: "txn-006",
    account_id: "demo-acct-001",
    type: "incoming",
    amount: 4200,
    currency: "USD",
    status: "completed",
    description: "Full product design sprint",
    reference: "BP-2024-0878",
    sender_name: "Zara Capital",
    sender_email: "payments@zaracap.com",
    created_at: "2024-07-10T13:22:00Z",
  },
];

export const DEMO_PAYMENT_LINKS: PaymentLink[] = [
  {
    id: "pl-001",
    account_id: "demo-acct-001",
    title: "Brand Identity Package",
    description: "Full brand identity: logo, guidelines, assets",
    amount: 1500,
    currency: "USD",
    status: "active",
    slug: "brand-identity-package",
    one_time: false,
    allow_customer_amount: false,
    total_collected: 7500,
    payment_count: 5,
    created_at: "2024-06-01T10:00:00Z",
  },
  {
    id: "pl-002",
    account_id: "demo-acct-001",
    title: "UI Design Retainer",
    description: "Monthly design retainer - 20 hrs/month",
    amount: 2400,
    currency: "USD",
    status: "active",
    slug: "ui-design-retainer",
    one_time: false,
    allow_customer_amount: false,
    total_collected: 9600,
    payment_count: 4,
    created_at: "2024-03-15T10:00:00Z",
  },
  {
    id: "pl-003",
    account_id: "demo-acct-001",
    title: "Logo Design",
    description: "Standalone logo design with revisions",
    amount: 450,
    currency: "USD",
    status: "active",
    slug: "logo-design",
    one_time: false,
    allow_customer_amount: false,
    total_collected: 2250,
    payment_count: 5,
    created_at: "2024-05-20T10:00:00Z",
  },
  {
    id: "pl-004",
    account_id: "demo-acct-001",
    title: "Custom Invoice",
    description: "Pay your invoice",
    amount: undefined,
    currency: "USD",
    status: "active",
    slug: "pay-invoice",
    one_time: false,
    allow_customer_amount: true,
    total_collected: 8400,
    payment_count: 7,
    created_at: "2024-04-10T10:00:00Z",
  },
];

export const DEMO_RECIPIENTS: Recipient[] = [
  {
    id: "rec-001",
    account_id: "demo-acct-001",
    name: "Adebayo Okonkwo",
    email: "ade@adebayodesigns.com",
    bank_name: "Guaranty Trust Bank",
    bank_account_number: "0123456789",
    bank_account_name: "ADEBAYO OKONKWO",
    country: "NG",
    currency: "NGN",
    is_verified: true,
    created_at: "2024-01-20T10:00:00Z",
  },
  {
    id: "rec-002",
    account_id: "demo-acct-001",
    name: "Kemi Adeyemi",
    email: "kemi@studio.co",
    bank_name: "First Bank of Nigeria",
    bank_account_number: "9876543210",
    bank_account_name: "KEMI ADEYEMI",
    country: "NG",
    currency: "NGN",
    is_verified: true,
    created_at: "2024-02-15T10:00:00Z",
  },
];

export const DEMO_SETTLEMENTS: Settlement[] = [
  {
    id: "set-001",
    account_id: "demo-acct-001",
    recipient_id: "rec-001",
    recipient: DEMO_RECIPIENTS[0],
    amount_usd: 3200,
    amount_local: 4_950_400,
    local_currency: "NGN",
    exchange_rate: 1547,
    fee_usd: 8.5,
    status: "settled",
    reference: "SET-2024-0045",
    note: "Monthly settlement",
    created_at: "2024-07-14T08:00:00Z",
    completed_at: "2024-07-14T10:32:00Z",
  },
  {
    id: "set-002",
    account_id: "demo-acct-001",
    recipient_id: "rec-001",
    recipient: DEMO_RECIPIENTS[0],
    amount_usd: 2100,
    amount_local: 3_248_700,
    local_currency: "NGN",
    exchange_rate: 1547,
    fee_usd: 6.0,
    status: "settled",
    reference: "SET-2024-0038",
    created_at: "2024-07-01T08:00:00Z",
    completed_at: "2024-07-01T10:15:00Z",
  },
  {
    id: "set-003",
    account_id: "demo-acct-001",
    recipient_id: "rec-002",
    recipient: DEMO_RECIPIENTS[1],
    amount_usd: 800,
    amount_local: 1_237_600,
    local_currency: "NGN",
    exchange_rate: 1547,
    fee_usd: 3.5,
    status: "processing",
    reference: "SET-2024-0051",
    note: "Subcontractor payment",
    created_at: "2024-07-19T09:00:00Z",
  },
];

export const DEMO_STATS: DashboardStats = {
  total_received_usd: 28_450,
  total_received_change: 23.4,
  pending_settlements_usd: 800,
  active_payment_links: 4,
  transactions_this_month: 11,
  avg_transaction_usd: 1580,
};

export const DEMO_CHART_DATA: ChartDataPoint[] = [
  { date: "Jul 1", amount: 4200, count: 2 },
  { date: "Jul 3", amount: 1100, count: 1 },
  { date: "Jul 5", amount: 2800, count: 1 },
  { date: "Jul 7", amount: 0, count: 0 },
  { date: "Jul 9", amount: 1500, count: 1 },
  { date: "Jul 11", amount: 3200, count: 2 },
  { date: "Jul 13", amount: 750, count: 1 },
  { date: "Jul 15", amount: 2100, count: 1 },
  { date: "Jul 17", amount: 1500, count: 1 },
  { date: "Jul 19", amount: 320, count: 1 },
];

// Demo mode is enabled by default (useAppStore.isDemoMode = true)
// All data above is seed data for the hackathon demo.
// In production, replace service.ts mock responses with real Busha API calls.
